export default {
    en: {
        address: 'Address',
        addresses: 'Addresses',
        cancel: 'Cancel',
        changePassword: 'Change Password',
        city: 'City',
        confirmPassword: 'Confirm New Password',
        country: 'Country',
        delete: 'Delete',
        deleteAddress: 'Delete Address',
        deleteAddressConfirm: 'Are you sure you want to delete the address?',
        details: 'Details',
        edit: 'Edit',
        editAddress: 'Edit Address',
        editDetails: 'Edit Details',
        email: 'Email',
        fieldRequired: 'This field is required',
        name: 'Full Name',
        newAddress: 'New Address',
        newPassword: 'New Password',
        oldPassword: 'Old Password',
        passwordMismatch: 'Passwords don\'t match',
        phoneNumber: 'Phone Number',
        postalCode: 'Postal Code',
        save: 'Save',
        state: 'State',
        title: 'My Account',
        update: 'Update',
        vatin: 'VAT Identification Number',
        vatLabel: 'VAT'

    },
    jp: {
        address: '住所',
        addresses: '住所',
        cancel: 'キャンセル',
        changePassword: 'パスワードの変更',
        city: ' 都市',
        confirmPassword: '新しいパスワードの確認',
        country: '国',
        delete: '削除',
        deleteAddress: '住所削除',
        deleteAddressConfirm: '本当に削除しますか？',
        details: '詳細',
        edit: '編集',
        editAddress: '住所の編集',
        editDetails: '詳細を編集',
        email: 'E-Mail',
        fieldRequired: 'このフィールドは必須です',
        name: '名前',
        newAddress: '新しい住所',
        newPassword: '新しいパスワード',
        oldPassword: '古いパスワード',
        passwordMismatch: 'パスワードは一致しません',
        phoneNumber: '電話番号',
        postalCode: '電話番号',
        save: '保存',
        state: 'State',
        title: 'アカウント詳細',
        update: '更新',
        vatin: 'VAT 番号',
        vatLabel: 'VAT'
    }
};
