export default {
    en: {
        billingDetails: 'Billing Information',
        createdAt: 'Created at',
        customer: 'Customer',
        id: 'ID',
        nameHeading: 'Name',
        paymentMethod: 'Payment Method',
        priceHeading: 'Price',
        products: 'Products',
        quantityHeading: 'Qty.',
        shipping: 'Shipping',
        shippingCost: 'Shipping Cost',
        shippingDetails: 'Shipping Information',
        shippingMethod: 'Shipping Method',
        skuHeading: 'SKU',
        status: 'Status',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'VAT'
    },
    jp: {
        billingDetails: '請求情報',
        createdAt: '作成日時',
        customer: 'お客様',
        id: 'ID',
        nameHeading: '名前',
        paymentMethod: '支払い方法',
        priceHeading: '価格',
        products: '商品',
        quantityHeading: '数量.',
        shipping: '配送',
        shippingCost: '送料',
        shippingDetails: '配送情報',
        shippingMethod: '配送方法',
        skuHeading: 'SKU',
        status: 'ステータス',
        subTotal: '小計',
        total: '合計',
        vat: 'VAT'
    }
};
