export default {
    en: {
        back: 'Back',
        categories: 'Categories',
        collections: 'Collections',
        currency: 'Currency',
        delete: 'Delete',
        description: 'Description',
        enabled: 'Enabled',
        fieldRequired: 'This field is required',
        homepage: 'Homepage',
        listPrice: 'List Price',
        mainCategory: 'Main Category',
        mainCollection: 'Main Collection',
        name: 'Name',
        pricing: 'Pricing',
        retailPrice: 'Retail Price',
        save: 'Save',
        sections: 'Featured in Sections',
        sku: 'SKU',
        stock: 'Stock',
        title: 'Edit Product',
        type: 'Type',
        vat: '% VAT (Included)',
        others: 'Details',
        location: 'Location',
        duration: 'Duration',
        provided: 'Plan',
        schedule: 'Schedule',
        day: 'Day'
    },
    jp: {
        back: '戻る',
        categories: 'カテゴリー',
        collections: '収集',
        currency: '通貨',
        delete: '削除',
        description: '説明',
        enabled: '使用可能',
        fieldRequired: 'このフィールドは必須です',
        homepage: 'ホーム',
        listPrice: '推奨価格',
        mainCategory: '主なカテゴリー',
        mainCollection: '主な収集',
        name: '名前',
        pricing: '価格',
        retailPrice: '終値',
        save: '保存',
        sections: 'セクションで紹介',
        sku: 'SKU',
        stock: '在庫',
        title: '編集製品',
        type: 'タイプ',
        vat: '% VAT（付属）',
        others: '詳細',
        location: 'ロケーション',
        duration: '期間',
        provided: '含む',
        schedule: 'スケジュール',
        day: '日'
    }
};
